#!/usr/bin/with-contenv sh

# Make sure to have a defined set of PHP binaries,
# regardless of how the package maintainer(s) named those.

rm /usr/bin/php
ln -s /usr/bin/php7 /usr/bin/php

rm /usr/sbin/php-fpm
ln -s /usr/sbin/php-fpm7 /usr/sbin/php-fpm
